In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers import Dense,Dropout,BatchNormalization,Activation
from keras.layers.core import Activation
from keras.layers.core import Dropout
#from keras.utils.np_utils import to_categorical
from tensorflow.keras.optimizers import SGD

In [2]:
def getdata(data):
    
    file = open(data, "r")
    f= file.readlines()

    newList= []
    
    for line in f:
        newList.append(line[1:-2])
    
    sonList=[]
    i=0
    for x in range(len(newList)-1):
        a=newList[x].split(",")
        sonList.append(a)
        i=i+1
    return sonList

In [3]:

def date_normalizer(date):
    #date='11.02.2022 09:30:03'
    dates=date.split(" ")
    date=dates[0]
    hours=dates[1]
    
    dates=date.split(".")
    
    days=int(dates[0])
    month=int(dates[1])
    
    dateseconds=(days*24+(month*30*24))*3600
    
    hours=hours.split(":")
    
    hour=int(hours[0])
    minute=int(hours[1])
    second=int(hours[2])
    
    output=dateseconds+(hour*3600)+(minute*60)+second
    return output

In [4]:

def general_normalizer(column):
    maximum_value=max(column)
    minumum_value=min(column)
    normalized_data=[]
    for r in column:
        new_r=(r-minumum_value)/(maximum_value-minumum_value)
        normalized_data.append(new_r)
    return normalized_data

In [59]:
data=getdata("DOHOL.txt")
df = pd.DataFrame(data=data)

df1=pd.to_numeric(df[1])
df11= pd.to_numeric(df[11])
price=df1
situation=[]
for i in range(0,len(price)):
    try:
        current_price=price[i]
        after_price=price[i+2]
        if current_price==after_price:
            situation.append(2) #Bekle
        elif current_price>after_price:
            situation.append(1) #SAT
        else:
            situation.append(0) #AL
    except:
        situation.append(2)

situation = pd.Series(situation)
df.insert(loc=20, column=20, value=situation)


for w in range(0,len(df)):
    df[0][w]=date_normalizer(df[0][w])
for c in range(0,len(df.columns)-1):
    counter=0
    for r in df[c]:
        
        df[c][counter]=float(r)
        
        counter+=1
    df[c]=general_normalizer(df[c])

C:\Users\OMERAT~1\AppData\Local\Temp/ipykernel_13712/73979073.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[0][w]=date_normalizer(df[0][w])
C:\Users\OMERAT~1\AppData\Local\Temp/ipykernel_13712/73979073.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[c][counter]=float(r)

In [60]:
df.head(10) # tüm veriler normalize

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.000000,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,...,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.033227,2.226888e-07,2
1,0.000000,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,...,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.033227,2.226888e-07,2
2,0.000000,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,...,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.033227,2.226888e-07,2
3,0.000006,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,...,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.040045,2.227938e-07,0
4,0.000009,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,...,0.388889,0.000675,0.388889,0.000912,0.388889,0.000649,0.388889,0.040045,2.227938e-07,0
5,0.000028,0.444444,0.000311,0.444444,0.074819,0.444444,0.014642,0.444444,0.014814,0.444444,...,0.444444,0.001215,0.444444,0.001857,0.444444,0.037750,0.444444,0.026409,2.544683e-07,2
6,0.000036,0.444444,0.000311,0.444444,0.074819,0.444444,0.014642,0.444444,0.014814,0.444444,...,0.444444,0.000338,0.444444,0.003207,0.444444,0.037750,0.444444,0.024591,2.544683e-07,2
7,0.000036,0.444444,0.000311,0.444444,0.074819,0.444444,0.014642,0.444444,0.014814,0.444444,...,0.444444,0.000338,0.444444,0.003207,0.444444,0.037750,0.444444,0.024591,2.544683e-07,2
8,0.000036,0.444444,0.000311,0.444444,0.074819,0.444444,0.014642,0.444444,0.014814,0.444444,...,0.444444,0.000338,0.444444,0.003207,0.444444,0.037750,0.444444,0.024591,2.544683e-07,2
9,0.000049,0.444444,0.000311,0.444444,0.074819,0.444444,0.014642,0.444444,0.014814,0.444444,...,0.444444,0.001080,0.444444,0.002735,0.444444,0.037750,0.444444,0.024591,2.544683e-07,2

In [95]:
trained=df.iloc[:,0:20]
y_data=df[20]

In [96]:
trained.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.000000,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,0.014825,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.033227,2.226888e-07
1,0.000000,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,0.014825,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.033227,2.226888e-07
2,0.000000,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,0.014825,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.033227,2.226888e-07
3,0.000006,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,0.014825,0.388889,0.001991,0.388889,0.000912,0.388889,0.000649,0.388889,0.040045,2.227938e-07
4,0.000009,0.388889,0.075197,0.388889,0.014419,0.388889,0.012443,0.388889,0.018704,0.388889,0.014825,0.388889,0.000675,0.388889,0.000912,0.388889,0.000649,0.388889,0.040045,2.227938e-07

In [97]:
y_data.head()

0    2
1    2
2    2
3    0
4    0
Name: 20, dtype: int64

# Veri bölme

In [112]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(trained, y_data, test_size = 0.25, random_state = 42)
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (13357, 20)
Training Labels Shape: (13357,)
Testing Features Shape: (4453, 20)
Testing Labels Shape: (4453,)

In [114]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
train_features= st_x.fit_transform(train_features)    
test_features= st_x.transform(test_features)

In [115]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [116]:
# Use the forest's predict method on the test data
predictions = rf.predict(train_features)
# Calculate the absolute errors
errors = abs(predictions - train_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.1 degrees.

In [117]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(predictions, train_labels))
print('Mean Squared Error:', metrics.mean_squared_error(predictions, train_labels))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(predictions, train_labels)))

Mean Absolute Error: 0.09910691080892481
Mean Squared Error: 0.0661122343547158
Root Mean Squared Error: 0.2571229946051419

In [118]:
import sklearn
mse = sklearn.metrics.mean_squared_error(predictions,train_labels )
rmse = math.sqrt(mse)
rmse= 1-rmse
print('Accuracy for Random Forest',100*max(0,rmse))

Accuracy for Random Forest 74.28770053948581

### test data

In [119]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)

In [120]:
import sklearn
mse = sklearn.metrics.mean_squared_error(predictions,test_labels )
rmse = math.sqrt(mse)
rmse= 1-rmse
print('Accuracy for Random Forest',100*max(0,rmse))

Accuracy for Random Forest 56.062886954125716

In [128]:
test_features[0:2]

array([[5.91169959e-01, 4.44444444e-01, 2.72512585e-01, 4.44444444e-01,
        6.34135776e-01, 4.44444444e-01, 6.06862314e-01, 4.44444444e-01,
        5.35687565e-01, 4.44444444e-01, 5.09808326e-01, 4.44444444e-01,
        2.09599028e-02, 4.44444444e-01, 4.30230595e-01, 4.44444444e-01,
        4.69947246e-01, 4.44444444e-01, 4.96954545e-01, 2.54731298e-07],
       [5.54861098e-01, 3.88888889e-01, 2.57535268e-01, 3.88888889e-01,
        4.92542855e-01, 3.88888889e-01, 6.89813360e-01, 3.88888889e-01,
        7.71734251e-01, 3.88888889e-01, 5.69631626e-01, 3.88888889e-01,
        3.57904685e-01, 3.88888889e-01, 3.51362301e-01, 3.88888889e-01,
        3.84588775e-01, 3.88888889e-01, 3.54000000e-01, 2.22664491e-07]])

In [129]:
predictions = rf.predict(test_features[0:20])

In [131]:
import sklearn
mse = sklearn.metrics.mean_squared_error(predictions,test_labels[20:40] )
rmse = math.sqrt(mse)
rmse= 1-rmse
print('Accuracy for Random Forest',100*max(0,rmse))

Accuracy for Random Forest 78.2611288544629